services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moto_planck_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
      - ./logs:/var/log/postgresql

volumes:
  database:
  logs: